; input_scan_code_set1.asm
; author: Lucas Bertho
; date: 10/28/2022

[bits 64]
input_scan_code_set1: db 0x01
key_escape_down:      db 0
key_1_down:           db '1'
key_2_down:           db '2'
key_3_down:           db '3'
key_4_down:           db '4'
key_5_down:           db '5'
key_6_down:           db '6'
key_7_down:           db '7'
key_8_down:           db '8'
key_9_down:           db '9'
key_0_down:           db '0'
key_minus_down:       db '-'
key_equal_down:       db '='
key_backspace_down:   db 0
key_tab_down:         db 0
key_q_down:           db 'q'
key_w_down:           db 'w'
key_e_down:           db 'e'
key_r_down:           db 'r'
key_t_down:           db 't'
key_y_down:           db 'y'
key_u_down:           db 'u'
key_i_down:           db 'i'
key_o_down:           db 'o'
key_p_down:           db 'p'
key_lbrace_down:      db '['
key_rbrace_down:      db ']'
key_enter_down:       db 0x0a
key_lctrl_down:       db 0
key_a_down:           db 'a'
key_s_down:           db 's'
key_d_down:           db 'd'
key_f_down:           db 'f'
key_g_down:           db 'g'
key_h_down:           db 'h'
key_j_down:           db 'j'
key_k_down:           db 'k'
key_l_down:           db 'l'
key_semicolon_down:   db ';'
key_apostrophe_down:  db 0x27
key_grave_down:       db '`'
key_lshift_down:      db 0
key_backslash_down:   db '\'
key_z_down:           db 'z'
key_x_down:           db 'x'
key_c_down:           db 'c'
key_v_down:           db 'v'
key_b_down:           db 'b'
key_n_down:           db 'n'
key_m_down:           db 'm'
key_comma_down:       db ','
key_dot_down:         db '.'
key_slash_down:       db '/'
key_rshift_down:      db 0
key_asterisk_down:    db '*'
key_lalt_down:        db 0
key_space_down:       db ' '
key_capslock_down:    db 0
key_f1_down:          db 0
key_f2_down:          db 0
key_f3_down:          db 0
key_f4_down:          db 0
key_f5_down:          db 0
key_f6_down:          db 0
key_f7_down:          db 0
key_f8_down:          db 0
key_f9_down:          db 0
key_f10_down:         db 0
key_numlock_down:     db 0
key_scrolllock_down:  db 0
key_kp7_down:         db '7'    ; key pad
key_kp8_down:         db '8'
key_kp9_down:         db '9'
key_kpminus_down:     db '-'
key_kp4_down:         db '4'
key_kp5_down:         db '5'
key_kp6_down:         db '6'
key_kpplus_down:      db '+'
key_kp1_down:         db '1'
key_kp2_down:         db '2'
key_kp3_down:         db '3'
key_kp0_down:         db '0'
key_kpdot_down:       db '.'
times (255-83) db 0