lkernel_color_fg_black              equ 0x00
lkernel_color_fg_blue               equ 0x01
lkernel_color_fg_green              equ 0x02
lkernel_color_fg_cyan               equ 0x03
lkernel_color_fg_red                equ 0x04
lkernel_color_fg_magenta            equ 0x05
lkernel_color_fg_brown              equ 0x06
lkernel_color_fg_light_gray         equ 0x07
lkernel_color_fg_dark_gray          equ 0x08
lkernel_color_fg_light_blue         equ 0x09
lkernel_color_fg_light_green        equ 0x0a
lkernel_color_fg_light_cyan         equ 0x0b
lkernel_color_fg_light_red          equ 0x0c
lkernel_color_fg_light_magenta      equ 0x0d
lkernel_color_fg_yellow             equ 0x0e
lkernel_color_fg_white              equ 0x0f

lkernel_color_bg_black              equ 0x00
lkernel_color_bg_blue               equ 0x10
lkernel_color_bg_green              equ 0x20
lkernel_color_bg_cyan               equ 0x30
lkernel_color_bg_red                equ 0x40
lkernel_color_bg_magenta            equ 0x50
lkernel_color_bg_brown              equ 0x60
lkernel_color_bg_light_gray         equ 0x70
lkernel_color_bg_blinking_black     equ 0x80
lkernel_color_bg_blinking_blue      equ 0x90
lkernel_color_bg_blinking_green     equ 0xa0
lkernel_color_bg_blinking_cyan      equ 0xb0
lkernel_color_bg_blinking_red       equ 0xc0
lkernel_color_bg_blinking_magenta   equ 0xd0
lkernel_color_bg_blinking_yellow    equ 0xe0
lkernel_color_bg_blinking_white     equ 0xf0